### ISSUE TITLE
can't debug in-package actions

### ISSUE THREAD

**Issue by triceam** [apache/openwhisk-debugger#18]
Attempting to debug an action within a package does not work.

I have these actions: 
![image](https://cloud.githubusercontent.com/assets/974294/21114439/172d8e2c-c07b-11e6-8d67-4ba55eb8a932.png)

However, nothing happens when I try to debug using:
`invoke overwatch/analysis -p doc {"id":"804B8B47-F86D-43C1-9395-63E34202C10D"}`

For example, it just sits here: 
![image](https://cloud.githubusercontent.com/assets/974294/21114458/27d7166c-c07b-11e6-8106-181e4fcb6aec.png)

**Comment by starpit** [comment]
there is a backend openwhisk API limitation here: https://github.com/openwhisk/openwhisk/issues/1635

in the mean time, we should investigate working around this limitation.
