### ISSUE TITLE
Error: getaddrinfo ENOTFOUND owdbg-broker.mybluemix.net owdbg-broker.mybluemix.net:443

### ISSUE THREAD

**Issue by Katiyman** [apache/openwhisk-debugger#30]
I have a local openwhisk setup on ubuntu 16.04.
I followed your instruction for installation of openwhisk debugger.
post the successful installation when i run wskdb command i get the below error:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND owdbg-broker.mybluemix.net owdbg-broker.mybluemix.net:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

Kindly help

**Comment by starpit** [comment]
hello, thanks for the report!

can you `ping owdbg-broker.mybluemix.net` ?

**Comment by Katiyman** [comment]
ping is blocked in my org ..
i did wget and it is showing
Proxy request sent, awaiting response... 404 Not Found
2017-05-18 12:06:46 ERROR 404: Not Found.

**Comment by starpit** [comment]
thanks. are you using the Bluemix OpenWhisk, or one you have set up yourself? if the former, then i'm surprised, because if you can reach Bluemix OpenWhisk, you should be able to reach owdbg-broker.mybluemix.net... hmm

**Comment by rabbah** [comment]
This may be related to the general problem you're having connecting out from the action containers.

**Comment by Katiyman** [comment]
@rabbah  ok, once the other one is resolved will come back to this.

**Comment by Katiyman** [comment]
@starpit i have setup my self
