### ISSUE TITLE
Installation error, can't install debugger

### ISSUE THREAD

**Issue by ivgenyk** [apache/openwhisk-debugger#35]
Hi,
When trying to install the debugger the installation fails with the error stack that is attached bellow.
What am I doing wrong?
I have node 7.7.2 may this cause the problem?

C:\Qanta\openwhisk>npm install -g openwhisk-debugger

> v8-debug@0.7.7 preinstall C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\.staging\v8-debug-4d02095f
> node -e 'process.exit(0)'

> v8-profiler@5.6.5 preinstall C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\.staging\v8-profiler-623c07a6
> node -e 'process.exit(0)'

C:\Users\Ivgeny\AppData\Roaming\npm\wskdb -> C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\bin\wskdb

> v8-debug@0.7.7 install C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/node-v51-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and node@7.7.2 (node-v51 ABI) (falling back to source compile with node-gyp)

C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" clean )  else (node "" clean )

C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" configure --fallback-to-build --module=C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64 )  else (node "" configure --fallback-to-build --module=C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64 )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:454:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:480:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:114:15)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Ivgeny\\AppData\\Roaming\\npm\\node_modules\\openwhisk-debugger\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v51-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Users\\Ivgeny\\AppData\\Roaming\\npm\\node_modules\\openwhisk-debugger\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\node-v51-win32-x64"
gyp ERR! cwd C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug
gyp ERR! node -v v7.7.2
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:899:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Ivgeny\\AppData\\Roaming\\npm\\node_modules\\openwhisk-debugger\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug
node-pre-gyp ERR! node -v v7.7.2
node-pre-gyp ERR! node-pre-gyp -v v0.6.36
node-pre-gyp ERR! not ok
Failed to execute 'node-gyp.cmd configure --fallback-to-build --module=C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64\debug.node --module_name=debug --module_path=C:\Users\Ivgeny\AppData\Roaming\npm\node_modules\openwhisk-debugger\node_modules\v8-debug\build\debug\v0.7.7\node-v51-win32-x64' (1)
C:\Users\Ivgeny\AppData\Roaming\npm
`-- (empty)

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "openwhisk-debugger"
npm ERR! node v7.7.2
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Qanta\openwhisk\npm-debug.log

**Comment by mrutkows** [comment]
Hi @ivgenyk ,

According to the author of the debugger, Nick Mitchell, the debugger currently requires node 6 to 6.2, i believe. anything higher than 6.3 won't work.

It appears you are trying Node 8...  the community would welcome someone who can help us move this debugger to newer Node versions, but Nick indicated there were some known issues that prevented him from doing this without large changes.

**Comment by ivgenyk** [comment]
Thanks for the reply. I have changed to node 6.2.0 and the installation was successful.

**Comment by ivgenyk** [comment]
I have another issue that maybe you can help me with. I have run simple "hello world" action and the debugger crushed. Do you know why?
Both the code and the exception message are below:


(wskdb) inspect action_temp1
Attached = no
This is a nodejs:6 action
        function main(params){
            console.log("hello world in console.log");
            console.log(JSON.stringify(params.message));
            return {"result": "hello world",
                    "input": params.message
                }
        }
ok
(wskdb) attach action_temp1
Attaching to action_temp1
   Creating action trampoline
ok
(wskdb) invoke action_temp1 -p message "fkaljgla"
Debug session requested
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files (x86)\Nodist\bin\node_modules\openwhisk-debugger\node_modules\.bin\node-debug ENOENT
    at exports._errnoException (util.js:953:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

C:\Program Files (x86)\Nodist\bin>

**Comment by mrutkows** [comment]
@ivgenyk beyond making the recommendation above, I have no working knowledge of this codebase.

**Comment by starpit** [comment]
hi @ivgenyk sorry for the delay in responding to you. we've been working on an update to this functionality. check it out here: https://openwhisk.ng.bluemix.net/api/v1/web/nickm_wskng_demos/public/index.html

the OpenWhisk Shell includes the debugger functionality. in the Shell, the debugger works with all versions of node 6 (whereas this github project only works with up to NodeJS 6.2). Also, with the Shell, you can download a platform release, avoiding the need for any local builds. let us know what you think!

**Comment by gorkem** [comment]
@mrutkows @starpit Does the statement about OpenWhisk Shell above mean that this repository will no longer receive updates and has been abandoned by the original contributors?

**Comment by starpit** [comment]
hi @gorkem this particular repo is now dead. the replacement (which is all of the same code, plus some shell integration bits, and updates to support modern nodejs versions) is located here: https://github.com/ibm-functions/debugger

it runs as a shell plugin. with a shell version >= 1.3.395, you can:

```
plugin install @ibm-functions/debugger
<reload the shell>
let foo = x=>x
debug foo
```

this needs more user testing, so please consider the plugin experimental

**Comment by alibanaei** [comment]
@mrutkows
Hi, I'm using ubuntu 14.04
node v6.2.0
npm 1.3.10
I had this error when I wanted to install
![screenshot from 2019-01-09 12-51-05](https://user-images.githubusercontent.com/38518826/50889499-5a158180-140d-11e9-8044-9eda8f31aeff.png)


29 error Error: CERT_UNTRUSTED
29 error     at SecurePair.<anonymous> (tls.js:1370:32)
29 error     at SecurePair.EventEmitter.emit (events.js:92:17)
29 error     at SecurePair.maybeInitFinished (tls.js:982:10)
29 error     at CleartextStream.read [as _read] (tls.js:469:13)
29 error     at CleartextStream.Readable.read (_stream_readable.js:320:10)
29 error     at EncryptedStream.write [as _write] (tls.js:366:25)
29 error     at doWrite (_stream_writable.js:223:10)
29 error     at writeOrBuffer (_stream_writable.js:213:5)
29 error     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
29 error     at write (_stream_readable.js:583:24)
30 error If you need help, you may report this log at:
30 error     <http://github.com/isaacs/npm/issues>
30 error or email it to:
30 error     <npm-@googlegroups.com>
31 error System Linux 3.13.0-162-generic
32 error command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "openwhisk-debugger"
33 error cwd /home/ubuntu
34 error node -v v0.10.25
35 error npm -v 1.3.10
36 verbose exit [ 1, true ]

**Comment by alibanaei** [comment]
@mrutkows  would you pleas help me?

**Comment by rabbah** [comment]
@starpit is the shell of kui the new answer?
